import React, { useState, useRef, useEffect } from 'react';
import { 
  Terminal, Send, Sparkles, Brain, Cpu, Play, 
  RotateCcw, CheckCircle2, ChevronDown, ChevronRight, 
  Activity, ShieldCheck, Zap, Code, ShieldAlert
} from 'lucide-react';
import { useAdaptiveTheme } from '../../context/ThemeContext';

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  thoughts?: string[];
  toolCalls?: Array<{ tool: string; input: string; output: string }>;
  timestamp: string;
}

interface Props {
  agentName: string;
  designation: string;
  model: string;
  temperature: number;
  selectedTools: string[];
  systemPrompt: string;
}

export const AgentSandboxSimulator: React.FC<Props> = ({
  agentName,
  designation,
  model,
  temperature,
  selectedTools,
  systemPrompt,
}) => {
  const { currentTheme } = useAdaptiveTheme();

  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'init',
      role: 'assistant',
      content: `[${designation}] Entity core online. Neural parameters calibrated (Model: ${model.replace('gemini-', '')}, T=${temperature.toFixed(2)}, Active Tools: ${selectedTools.length}). Awaiting mission directive.`,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    },
  ]);

  const [inputPrompt, setInputPrompt] = useState<string>('');
  const [isProcessing, setIsProcessing] = useState<boolean>(false);
  const [expandedThoughts, setExpandedThoughts] = useState<Record<string, boolean>>({});
  const chatBottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatBottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isProcessing]);

  const toggleThoughts = (msgId: string) => {
    setExpandedThoughts(prev => ({ ...prev, [msgId]: !prev[msgId] }));
  };

  // Generate deterministic realistic offline simulated multi-step agent response
  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputPrompt.trim() || isProcessing) return;

    const userText = inputPrompt.trim();
    const userMsgId = Math.random().toString(36).substring(2, 8);
    const assistantMsgId = Math.random().toString(36).substring(2, 8);

    const userMsg: ChatMessage = {
      id: userMsgId,
      role: 'user',
      content: userText,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages(prev => [...prev, userMsg]);
    setInputPrompt('');
    setIsProcessing(true);

    setTimeout(() => {
      // Simulate multi-step CoT reasoning steps based on input
      const thoughts = [
        `Received directive: "${userText}"`,
        `Analyzing system prompt constraints for entity [${designation}]`,
        `Evaluating accessible tool matrix: [${selectedTools.slice(0, 3).join(', ')}${selectedTools.length > 3 ? '...' : ''}]`,
        `Applying deterministic sampling at T=${temperature.toFixed(2)} with strict safety guardrails`,
        `Synthesizing final structured response adherence`,
      ];

      // Simulated Tool calls
      const toolCalls: ChatMessage['toolCalls'] = [];
      if (selectedTools.includes('rag.vectorSearch') && (userText.toLowerCase().includes('search') || userText.toLowerCase().includes('find') || userText.toLowerCase().includes('data') || userText.length > 10)) {
        toolCalls.push({
          tool: 'rag.vectorSearch',
          input: `{"query": "${userText.substring(0, 30)}...", "topK": 3}`,
          output: `{"status": "resolved", "chunksMatched": 3, "similarityScore": 0.948}`,
        });
      }

      if (selectedTools.includes('fs.read') && userText.toLowerCase().includes('file')) {
        toolCalls.push({
          tool: 'fs.read',
          input: `{"path": "/src/core/pipeline.ts"}`,
          output: `{"bytes": 1420, "encoding": "utf-8", "sha256": "e3b0c442..."}`,
        });
      }

      if (selectedTools.includes('crypto.signPayload')) {
        toolCalls.push({
          tool: 'crypto.signPayload',
          input: `{"payloadHash": "0x7f83b1657...", "keyId": "${designation}-sec"}`,
          output: `{"signature": "sig_ed25519_9948fa11b", "verified": true}`,
        });
      }

      // Format response
      let content = `**[${designation} Execution Log]**\n\nDirective successfully processed with high confidence (99.4% alignment).\n\n`;
      if (userText.toLowerCase().includes('code') || userText.toLowerCase().includes('build') || userText.toLowerCase().includes('create')) {
        content += `\`\`\`typescript\n// Generated by ${agentName} (${designation})\nexport async function executePlan(): Promise<Result> {\n  const context = await retrieveContext();\n  return {\n    status: 'COMPLETED',\n    entity: '${designation}',\n    timestamp: Date.now(),\n  };\n}\n\`\`\`\n`;
      } else {
        content += `Analysis summary regarding: *"${userText}"*\n- **Status**: Verified & Deterministic\n- **Inference Latency**: 18.2ms (Simulated)\n- **Guardrail Check**: 0 Violations\n\nAll output parameters adhere to the prescribed zero-trust constraints.`;
      }

      const assistantMsg: ChatMessage = {
        id: assistantMsgId,
        role: 'assistant',
        content,
        thoughts,
        toolCalls: toolCalls.length > 0 ? toolCalls : undefined,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      };

      setMessages(prev => [...prev, assistantMsg]);
      setExpandedThoughts(prev => ({ ...prev, [assistantMsgId]: true }));
      setIsProcessing(false);
    }, 850);
  };

  const handleResetSandbox = () => {
    setMessages([
      {
        id: 'init',
        role: 'assistant',
        content: `[${designation}] Sandbox re-initialized. Ready for testing.`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      },
    ]);
  };

  return (
    <div 
      className="border rounded-2xl p-6 shadow-sm space-y-4 transition-all"
      style={{
        backgroundColor: currentTheme.palette.surface,
        borderColor: currentTheme.palette.border,
        color: currentTheme.palette.textPrimary,
      }}
    >
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b" style={{ borderColor: currentTheme.palette.border }}>
        <div className="flex items-center space-x-2.5">
          <div 
            className="w-8 h-8 rounded-lg flex items-center justify-center border"
            style={{
              backgroundColor: currentTheme.palette.surfaceRaised,
              borderColor: currentTheme.palette.borderStrong,
            }}
          >
            <Terminal className="w-4 h-4 text-emerald-400" />
          </div>
          <div>
            <h4 className="font-bold text-sm tracking-tight flex items-center space-x-1.5">
              <span>Interactive Sandbox Simulator</span>
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
            </h4>
            <p className="text-[11px] opacity-60">Test multi-turn reasoning traces, tool executions, and guardrail enforcement</p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleResetSandbox}
            className="px-2.5 py-1 rounded-lg border text-[11px] font-mono flex items-center space-x-1 hover:bg-white/5 transition-colors"
            style={{ borderColor: currentTheme.palette.borderStrong }}
          >
            <RotateCcw className="w-3 h-3" />
            <span>Reset Chat</span>
          </button>
        </div>
      </div>

      {/* Chat Messages Log */}
      <div 
        className="h-80 overflow-y-auto p-4 rounded-xl border space-y-4 font-mono text-xs shadow-inner"
        style={{
          backgroundColor: currentTheme.appearance === 'light' ? '#F9FAFB' : '#09090B',
          borderColor: currentTheme.palette.borderStrong,
        }}
      >
        {messages.map((msg) => {
          const isAssistant = msg.role === 'assistant';
          const hasThoughts = msg.thoughts && msg.thoughts.length > 0;
          const isThoughtsExpanded = expandedThoughts[msg.id] ?? false;

          return (
            <div key={msg.id} className={`flex flex-col space-y-1.5 ${isAssistant ? 'items-start' : 'items-end'}`}>
              <div className="flex items-center space-x-2 text-[10px] opacity-50 px-1">
                <span>{isAssistant ? `${agentName} (${designation})` : 'You (Operator)'}</span>
                <span>•</span>
                <span>{msg.timestamp}</span>
              </div>

              {/* Message Box */}
              <div 
                className={`max-w-[85%] rounded-xl p-3.5 border space-y-2.5 ${
                  isAssistant ? 'shadow-sm' : 'bg-indigo-600 text-white border-indigo-500'
                }`}
                style={isAssistant ? {
                  backgroundColor: currentTheme.palette.surfaceRaised,
                  borderColor: currentTheme.palette.border,
                  color: currentTheme.palette.textPrimary,
                } : {}}
              >
                {/* Expandable Chain of Thought block */}
                {hasThoughts && (
                  <div className="border rounded-lg overflow-hidden text-[11px]" style={{ borderColor: currentTheme.palette.borderStrong }}>
                    <button
                      onClick={() => toggleThoughts(msg.id)}
                      className="w-full px-2.5 py-1.5 flex items-center justify-between text-left opacity-75 hover:opacity-100 transition-opacity"
                      style={{ backgroundColor: currentTheme.palette.surface }}
                    >
                      <span className="flex items-center space-x-1.5 font-bold text-indigo-400">
                        <Brain className="w-3 h-3" />
                        <span>Chain-of-Thought Trace ({msg.thoughts?.length} Steps)</span>
                      </span>
                      {isThoughtsExpanded ? <ChevronDown className="w-3 h-3" /> : <ChevronRight className="w-3 h-3" />}
                    </button>

                    {isThoughtsExpanded && (
                      <div className="p-2.5 space-y-1 bg-black/20 border-t" style={{ borderColor: currentTheme.palette.borderStrong }}>
                        {msg.thoughts?.map((t, idx) => (
                          <div key={idx} className="flex items-start space-x-1.5 text-zinc-400">
                            <span className="opacity-40">{idx + 1}.</span>
                            <span>{t}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}

                {/* Simulated Tool Calls */}
                {msg.toolCalls && msg.toolCalls.map((tc, idx) => (
                  <div key={idx} className="p-2 rounded-lg bg-indigo-950/30 border border-indigo-500/30 text-[10px] space-y-1">
                    <div className="flex items-center justify-between text-indigo-300 font-bold">
                      <span className="flex items-center space-x-1">
                        <Zap className="w-3 h-3 text-amber-400" />
                        <span>Tool Invoked: {tc.tool}</span>
                      </span>
                      <span className="text-emerald-400">200 OK</span>
                    </div>
                    <div className="opacity-70 truncate font-mono">args: {tc.input}</div>
                    <div className="opacity-90 text-emerald-300 truncate font-mono">result: {tc.output}</div>
                  </div>
                ))}

                {/* Main Content */}
                <div className="whitespace-pre-wrap leading-relaxed">
                  {msg.content}
                </div>
              </div>
            </div>
          );
        })}

        {isProcessing && (
          <div className="flex items-center space-x-2 text-xs font-mono text-indigo-400 animate-pulse p-2">
            <Sparkles className="w-4 h-4 animate-spin" />
            <span>{agentName} is formulating chain-of-thought reasoning...</span>
          </div>
        )}
        <div ref={chatBottomRef} />
      </div>

      {/* Input Field */}
      <form onSubmit={handleSendMessage} className="flex items-center space-x-2">
        <input
          type="text"
          value={inputPrompt}
          onChange={(e) => setInputPrompt(e.target.value)}
          placeholder={`Instruct ${agentName}... (e.g., 'Review security architecture and write verification test')`}
          disabled={isProcessing}
          className="flex-1 px-4 py-2.5 rounded-xl border text-xs font-mono focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all disabled:opacity-50"
          style={{
            backgroundColor: currentTheme.appearance === 'light' ? '#FFFFFF' : '#09090B',
            borderColor: currentTheme.palette.borderStrong,
            color: currentTheme.palette.textPrimary,
          }}
        />
        <button
          type="submit"
          disabled={isProcessing || !inputPrompt.trim()}
          className="px-4 py-2.5 rounded-xl text-white font-mono font-bold text-xs flex items-center space-x-1.5 transition-all shadow-sm disabled:opacity-40"
          style={{ backgroundColor: currentTheme.palette.accent }}
        >
          <Send className="w-3.5 h-3.5" />
          <span>Send</span>
        </button>
      </form>
    </div>
  );
};
