import React, { useState } from 'react';
import { 
  FileCode, Download, Copy, Check, Terminal, 
  Layers, Sparkles, CheckCircle2, Box, Cpu 
} from 'lucide-react';
import { useAdaptiveTheme } from '../../context/ThemeContext';

interface Props {
  agentName: string;
  designation: string;
  model: string;
  temperature: number;
  topP: number;
  reasoningSteps: number;
  autonomyLevel: string;
  confidenceThreshold: number;
  memoryHorizon: string;
  selectedTools: string[];
  systemPrompt: string;
}

export const AgentExportHub: React.FC<Props> = ({
  agentName,
  designation,
  model,
  temperature,
  topP,
  reasoningSteps,
  autonomyLevel,
  confidenceThreshold,
  memoryHorizon,
  selectedTools,
  systemPrompt,
}) => {
  const { currentTheme } = useAdaptiveTheme();
  const [selectedFormat, setSelectedFormat] = useState<'json' | 'python' | 'yaml' | 'typescript' | 'docker'>('json');
  const [copied, setCopied] = useState(false);

  // Generate Gemini Manifest JSON
  const jsonManifest = JSON.stringify({
    schemaVersion: '2.0.0',
    entity: {
      name: agentName,
      designation,
      foundationModel: model,
      temperature,
      topP,
      reasoningBudgetSteps: reasoningSteps,
      autonomyTier: autonomyLevel,
      guardrailThreshold: confidenceThreshold / 100,
      memoryArchitecture: memoryHorizon,
    },
    systemDirectives: systemPrompt,
    tools: selectedTools.map(t => ({
      toolId: t,
      enabled: true,
      executionMode: 'isolated-sandbox',
    })),
    telemetry: {
      createdAt: new Date().toISOString(),
      provenance: 'ApexAI Autonomous Entity Forge',
      hash: 'sha256:4f89d12a80b...',
    }
  }, null, 2);

  // Generate Python LangGraph code
  const pythonCode = `"""
Autonomous Agent: ${agentName} (${designation})
Generated by ApexAI Entity Forge
"""

from typing import Annotated, Sequence, TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph import StateGraph, END
from google.genai import GoogleGenAI

# 1. Initialize Cognitive Engine
ai = GoogleGenAI(model="${model}")

SYSTEM_PROMPT = """${systemPrompt.replace(/"/g, '\\"')}"""

class AgentState(TypedDict):
    messages: Sequence[BaseMessage]
    thought_trace: list[str]
    active_tools: list[str]

def reasoning_node(state: AgentState) -> dict:
    # Execute deterministic CoT reasoning
    response = ai.generate_content(
        contents=state["messages"],
        temperature=${temperature},
        top_p=${topP},
        system_instruction=SYSTEM_PROMPT
    )
    return {"messages": [response], "thought_trace": ["Executed step"]}

# 2. Compile LangGraph Pipeline
workflow = StateGraph(AgentState)
workflow.add_node("agent", reasoning_node)
workflow.set_entry_point("agent")
workflow.add_edge("agent", END)

app = workflow.compile()
print("Entity [${designation}] loaded successfully.")
`;

  // Generate CrewAI YAML
  const yamlCode = `name: ${agentName}
designation: ${designation}
version: "1.0.0"
role: Autonomous Special Operations Agent
goal: Execute deterministic directives with zero-trust security
backstory: |
  ${systemPrompt.split('\n').join('\n  ')}

llm:
  model: ${model}
  temperature: ${temperature}
  top_p: ${topP}
  max_reasoning_steps: ${reasoningSteps}

capabilities:
  autonomy: ${autonomyLevel}
  memory_horizon: ${memoryHorizon}
  hallucination_guardrail: ${confidenceThreshold}%

tools:
${selectedTools.map(t => `  - ${t}`).join('\n')}

security_policies:
  zero_trust: true
  signed_payloads: true
  audit_logging: strict
`;

  // Generate TypeScript Runtime
  const typescriptCode = `import { GoogleGenAI } from "@google/genai";

export interface AgentConfig {
  name: string;
  designation: string;
  model: string;
  temperature: number;
}

export class ${agentName.replace(/[^a-zA-Z0-9]/g, '')}Agent {
  private ai: GoogleGenAI;
  private readonly config: AgentConfig = {
    name: "${agentName}",
    designation: "${designation}",
    model: "${model}",
    temperature: ${temperature},
  };

  constructor() {
    this.ai = new GoogleGenAI();
  }

  public async executeDirective(goal: string): Promise<string> {
    const response = await this.ai.generateContent({
      model: this.config.model,
      contents: goal,
      config: {
        temperature: this.config.temperature,
        systemInstruction: \`${systemPrompt.replace(/`/g, '\\`')}\`,
      },
    });

    return response.text || "";
  }
}
`;

  // Generate Dockerfile
  const dockerfileCode = `# ApexAI Autonomous Agent Container
FROM node:22-alpine AS runner
WORKDIR /app

# Install security certificates & zero-trust boundaries
RUN apk add --no-cache ca-certificates tini

COPY package*.json ./
RUN npm ci --only=production

COPY dist/ ./dist/

ENV NODE_ENV=production
ENV AGENT_DESIGNATION="${designation}"
ENV AGENT_TEMPERATURE="${temperature}"

USER node
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "dist/agent.cjs"]
`;

  const getCode = () => {
    switch (selectedFormat) {
      case 'json': return jsonManifest;
      case 'python': return pythonCode;
      case 'yaml': return yamlCode;
      case 'typescript': return typescriptCode;
      case 'docker': return dockerfileCode;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const extensions: Record<string, string> = {
      json: 'manifest.json',
      python: 'agent_graph.py',
      yaml: 'agent_spec.yaml',
      typescript: 'Agent.ts',
      docker: 'Dockerfile',
    };
    const filename = `${designation.toLowerCase()}_${extensions[selectedFormat]}`;
    const blob = new Blob([getCode()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div 
      className="border rounded-2xl p-6 shadow-sm space-y-4 transition-all"
      style={{
        backgroundColor: currentTheme.palette.surface,
        borderColor: currentTheme.palette.border,
        color: currentTheme.palette.textPrimary,
      }}
    >
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b" style={{ borderColor: currentTheme.palette.border }}>
        <div className="flex items-center space-x-2.5">
          <div 
            className="w-8 h-8 rounded-lg flex items-center justify-center border"
            style={{
              backgroundColor: currentTheme.palette.surfaceRaised,
              borderColor: currentTheme.palette.borderStrong,
            }}
          >
            <FileCode className="w-4 h-4 text-purple-400" />
          </div>
          <div>
            <h4 className="font-bold text-sm tracking-tight">Deployment & Export Manifest Hub</h4>
            <p className="text-[11px] opacity-60">Export agent architecture across standard production frameworks</p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopy}
            className="px-3 py-1.5 rounded-lg border text-xs font-mono flex items-center space-x-1.5 hover:bg-white/5 transition-colors"
            style={{ borderColor: currentTheme.palette.borderStrong }}
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Spec'}</span>
          </button>
          <button
            onClick={handleDownload}
            className="px-3 py-1.5 rounded-lg text-white font-mono font-bold text-xs flex items-center space-x-1.5 shadow-sm transition-all hover:opacity-90"
            style={{ backgroundColor: currentTheme.palette.accent }}
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Spec</span>
          </button>
        </div>
      </div>

      {/* Format Selector Pills */}
      <div className="flex flex-wrap gap-1.5">
        {[
          { id: 'json' as const, label: 'Gemini Manifest (JSON)' },
          { id: 'python' as const, label: 'LangGraph Pipeline (Python)' },
          { id: 'yaml' as const, label: 'CrewAI Blueprint (YAML)' },
          { id: 'typescript' as const, label: 'TypeScript SDK Class' },
          { id: 'docker' as const, label: 'Production Dockerfile' },
        ].map((fmt) => {
          const isSelected = selectedFormat === fmt.id;
          return (
            <button
              key={fmt.id}
              onClick={() => setSelectedFormat(fmt.id)}
              className={`px-3 py-1 rounded-md text-xs font-mono font-semibold border transition-all ${
                isSelected 
                  ? 'bg-indigo-500/20 text-indigo-300 border-indigo-500 shadow-xs' 
                  : 'opacity-70 hover:opacity-100'
              }`}
              style={!isSelected ? {
                backgroundColor: currentTheme.palette.surfaceRaised,
                borderColor: currentTheme.palette.borderStrong,
              } : {}}
            >
              {fmt.label}
            </button>
          );
        })}
      </div>

      {/* Code Viewer */}
      <pre 
        className="p-4 rounded-xl text-xs font-mono overflow-x-auto leading-relaxed border max-h-72"
        style={{
          backgroundColor: currentTheme.appearance === 'light' ? '#18181B' : '#09090B',
          borderColor: '#27272A',
          color: '#E4E4E7',
        }}
      >
        <code>{getCode()}</code>
      </pre>
    </div>
  );
};
