import { FocusAreaTheme, DensityMode } from '../types/theme';

export const FOCUS_AREA_THEMES: Record<string, FocusAreaTheme> = {
  ide: {
    id: 'theme-ide',
    tabId: 'ide',
    name: 'Cyber Matrix Pro',
    focusArea: 'Code IDE & Terminal',
    tagline: 'High-Contrast Dark Studio with Monospace Density',
    description: 'Engineered for low ocular fatigue, intense syntax differentiation, and maximum code lines visible per viewport.',
    appearance: 'dark',
    recommendedDensity: 'compact',
    fontVibe: 'mono-code',
    palette: {
      bg: '#080c14',
      bgGradient: 'radial-gradient(ellipse 80% 80% at 50% -20%, rgba(14, 165, 233, 0.15), rgba(8, 12, 20, 1))',
      bgSubtle: '#0d131f',
      surface: '#0f172a',
      surfaceRaised: '#1e293b',
      surfaceHover: '#1e293b',
      border: '#1e293b',
      borderStrong: '#334155',
      borderHighlight: '#06b6d4',
      textPrimary: '#f8fafc',
      textSecondary: '#94a3b8',
      textMuted: '#64748b',
      accent: '#06b6d4',
      accentHover: '#22d3ee',
      accentLight: 'rgba(6, 182, 212, 0.15)',
      accentText: '#67e8f9',
      accentGlow: '0 0 24px rgba(6, 182, 212, 0.35)',
      badgeBg: 'rgba(6, 182, 212, 0.18)',
      badgeText: '#38bdf8',
      codeBg: '#05070c',
      codeText: '#38bdf8',
      headerBg: 'rgba(8, 12, 20, 0.95)',
      sidebarBg: '#0b101c',
    },
    cssVariables: {
      '--app-bg': '#080c14',
      '--app-surface': '#0f172a',
      '--app-surface-raised': '#1e293b',
      '--app-border': '#1e293b',
      '--app-border-strong': '#334155',
      '--app-text-primary': '#f8fafc',
      '--app-text-secondary': '#94a3b8',
      '--app-text-muted': '#64748b',
      '--app-accent': '#06b6d4',
      '--app-accent-rgb': '6, 182, 212',
      '--app-accent-glow': 'rgba(6, 182, 212, 0.4)',
      '--app-card-radius': '6px',
      '--app-font-family': 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    },
    densityMetrics: {
      paddingCard: 'p-3 sm:p-4',
      paddingButton: 'px-2.5 py-1 text-xs',
      gapSection: 'space-y-3 gap-3',
      fontSizeBody: 'text-xs sm:text-sm',
      fontSizeHeading: 'text-xl sm:text-2xl font-mono tracking-tight',
      tableRowHeight: 'py-1.5 px-2 text-xs',
      codeFontSize: 'text-xs font-mono leading-tight',
    },
  },

  research: {
    id: 'theme-research',
    tabId: 'research',
    name: 'Calm Scholar & Ivory Paper',
    focusArea: 'Academic Research & Literature',
    tagline: 'Warm Soothing Parchment with Relaxed Editorial Typography',
    description: 'Designed for prolonged scholarly reading, relaxed cognitive flow, and distraction-free paper composition.',
    appearance: 'warm-light',
    recommendedDensity: 'relaxed',
    fontVibe: 'serif-scholar',
    palette: {
      bg: '#faf7f2',
      bgGradient: 'linear-gradient(180deg, #faf7f2 0%, #f4ede2 100%)',
      bgSubtle: '#f4ede2',
      surface: '#ffffff',
      surfaceRaised: '#ffffff',
      surfaceHover: '#f9f6f0',
      border: '#e4dacf',
      borderStrong: '#cfc0b0',
      borderHighlight: '#2d6a4f',
      textPrimary: '#1c1917',
      textSecondary: '#57534e',
      textMuted: '#78716c',
      accent: '#2d6a4f',
      accentHover: '#1e4635',
      accentLight: 'rgba(45, 106, 79, 0.12)',
      accentText: '#1e4635',
      accentGlow: '0 0 20px rgba(45, 106, 79, 0.18)',
      badgeBg: '#e8f3ee',
      badgeText: '#1b4332',
      codeBg: '#f2ece4',
      codeText: '#2d6a4f',
      headerBg: 'rgba(250, 247, 242, 0.95)',
      sidebarBg: '#f6f0e7',
    },
    cssVariables: {
      '--app-bg': '#faf7f2',
      '--app-surface': '#ffffff',
      '--app-surface-raised': '#ffffff',
      '--app-border': '#e4dacf',
      '--app-border-strong': '#cfc0b0',
      '--app-text-primary': '#1c1917',
      '--app-text-secondary': '#57534e',
      '--app-text-muted': '#78716c',
      '--app-accent': '#2d6a4f',
      '--app-accent-rgb': '45, 106, 79',
      '--app-accent-glow': 'rgba(45, 106, 79, 0.2)',
      '--app-card-radius': '10px',
      '--app-font-family': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    densityMetrics: {
      paddingCard: 'p-6 sm:p-8',
      paddingButton: 'px-4 py-2.5 text-sm',
      gapSection: 'space-y-8 gap-6',
      fontSizeBody: 'text-sm sm:text-base leading-relaxed',
      fontSizeHeading: 'text-2xl sm:text-3xl font-semibold tracking-tight font-serif',
      tableRowHeight: 'py-3.5 px-4 text-sm',
      codeFontSize: 'text-sm font-mono leading-relaxed',
    },
  },

  quantum: {
    id: 'theme-quantum',
    tabId: 'quantum',
    name: 'Superconducting Ion Cyan',
    focusArea: 'Quantum Computing & QPU Lab',
    tagline: 'Deep Ion Dark Canvas with Coherent Optical Glowing Telemetry',
    description: 'High-precision telemetry theme optimized for quantum gate state vectors, Bloch spheres, and Hamiltonian optimization.',
    appearance: 'cyber-dark',
    recommendedDensity: 'compact',
    fontVibe: 'cyber-tech',
    palette: {
      bg: '#040714',
      bgGradient: 'radial-gradient(circle at 50% 0%, rgba(139, 92, 246, 0.18), rgba(4, 7, 20, 1))',
      bgSubtle: '#090e24',
      surface: '#0b112c',
      surfaceRaised: '#131b3e',
      surfaceHover: '#18234d',
      border: '#1c2856',
      borderStrong: '#2d3d7c',
      borderHighlight: '#8b5cf6',
      textPrimary: '#f1f5f9',
      textSecondary: '#94a3b8',
      textMuted: '#64748b',
      accent: '#a855f7',
      accentHover: '#c084fc',
      accentLight: 'rgba(168, 85, 247, 0.16)',
      accentText: '#d8b4fe',
      accentGlow: '0 0 28px rgba(168, 85, 247, 0.4)',
      badgeBg: 'rgba(139, 92, 246, 0.2)',
      badgeText: '#c084fc',
      codeBg: '#060a1e',
      codeText: '#38bdf8',
      headerBg: 'rgba(4, 7, 20, 0.95)',
      sidebarBg: '#080d26',
    },
    cssVariables: {
      '--app-bg': '#040714',
      '--app-surface': '#0b112c',
      '--app-surface-raised': '#131b3e',
      '--app-border': '#1c2856',
      '--app-border-strong': '#2d3d7c',
      '--app-text-primary': '#f1f5f9',
      '--app-text-secondary': '#94a3b8',
      '--app-text-muted': '#64748b',
      '--app-accent': '#8b5cf6',
      '--app-accent-rgb': '139, 92, 246',
      '--app-accent-glow': 'rgba(139, 92, 246, 0.45)',
      '--app-card-radius': '8px',
      '--app-font-family': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    densityMetrics: {
      paddingCard: 'p-3.5 sm:p-4',
      paddingButton: 'px-3 py-1.5 text-xs',
      gapSection: 'space-y-4 gap-3',
      fontSizeBody: 'text-xs sm:text-sm',
      fontSizeHeading: 'text-xl sm:text-2xl font-bold tracking-tight',
      tableRowHeight: 'py-2 px-3 text-xs',
      codeFontSize: 'text-xs font-mono',
    },
  },

  engineering: {
    id: 'theme-engineering',
    tabId: 'engineering',
    name: 'Industrial Tactical Slate',
    focusArea: 'Global Engineering & Ops Solver',
    tagline: 'High-Density Mission Control & Alert Amber Diagnostics',
    description: 'Maximized information density for latency tracing, multi-region cluster topologies, and live outage recovery.',
    appearance: 'dark',
    recommendedDensity: 'compact',
    fontVibe: 'clean-slate',
    palette: {
      bg: '#0a0f1d',
      bgGradient: 'linear-gradient(180deg, #0a0f1d 0%, #060a14 100%)',
      bgSubtle: '#0f172a',
      surface: '#111827',
      surfaceRaised: '#1f2937',
      surfaceHover: '#1f2937',
      border: '#1f2937',
      borderStrong: '#374151',
      borderHighlight: '#f59e0b',
      textPrimary: '#f9fafb',
      textSecondary: '#9ca3af',
      textMuted: '#6b7280',
      accent: '#f59e0b',
      accentHover: '#fbbf24',
      accentLight: 'rgba(245, 158, 11, 0.15)',
      accentText: '#fde68a',
      accentGlow: '0 0 20px rgba(245, 158, 11, 0.3)',
      badgeBg: 'rgba(245, 158, 11, 0.18)',
      badgeText: '#fcd34d',
      codeBg: '#090d16',
      codeText: '#fbbf24',
      headerBg: 'rgba(10, 15, 29, 0.95)',
      sidebarBg: '#0c1222',
    },
    cssVariables: {
      '--app-bg': '#0a0f1d',
      '--app-surface': '#111827',
      '--app-surface-raised': '#1f2937',
      '--app-border': '#1f2937',
      '--app-border-strong': '#374151',
      '--app-text-primary': '#f9fafb',
      '--app-text-secondary': '#9ca3af',
      '--app-text-muted': '#6b7280',
      '--app-accent': '#f59e0b',
      '--app-accent-rgb': '245, 158, 11',
      '--app-accent-glow': 'rgba(245, 158, 11, 0.35)',
      '--app-card-radius': '6px',
      '--app-font-family': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    densityMetrics: {
      paddingCard: 'p-3 sm:p-4',
      paddingButton: 'px-3 py-1.5 text-xs',
      gapSection: 'space-y-3.5 gap-3',
      fontSizeBody: 'text-xs sm:text-sm',
      fontSizeHeading: 'text-xl sm:text-2xl font-bold tracking-tight',
      tableRowHeight: 'py-1.5 px-3 text-xs',
      codeFontSize: 'text-xs font-mono',
    },
  },

  opensource: {
    id: 'theme-opensource',
    tabId: 'opensource',
    name: 'Git Matrix Emerald',
    focusArea: 'Open Source Hub & Contributions',
    tagline: 'Clean Modern Studio with Git-Inspired Branch Emerald & Violet',
    description: 'Crisp code diffing, branch review badges, and high-visibility PR audit clarity.',
    appearance: 'light',
    recommendedDensity: 'balanced',
    fontVibe: 'sans-modern',
    palette: {
      bg: '#f8fafc',
      bgGradient: 'linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%)',
      bgSubtle: '#f1f5f9',
      surface: '#ffffff',
      surfaceRaised: '#ffffff',
      surfaceHover: '#f8fafc',
      border: '#e2e8f0',
      borderStrong: '#cbd5e1',
      borderHighlight: '#10b981',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textMuted: '#64748b',
      accent: '#059669',
      accentHover: '#047857',
      accentLight: 'rgba(16, 185, 129, 0.12)',
      accentText: '#047857',
      accentGlow: '0 0 16px rgba(16, 185, 129, 0.25)',
      badgeBg: '#ecfdf5',
      badgeText: '#065f46',
      codeBg: '#0f172a',
      codeText: '#34d399',
      headerBg: 'rgba(255, 255, 255, 0.95)',
      sidebarBg: '#f8fafc',
    },
    cssVariables: {
      '--app-bg': '#f8fafc',
      '--app-surface': '#ffffff',
      '--app-surface-raised': '#ffffff',
      '--app-border': '#e2e8f0',
      '--app-border-strong': '#cbd5e1',
      '--app-text-primary': '#0f172a',
      '--app-text-secondary': '#475569',
      '--app-text-muted': '#64748b',
      '--app-accent': '#059669',
      '--app-accent-rgb': '5, 150, 105',
      '--app-accent-glow': 'rgba(16, 185, 129, 0.25)',
      '--app-card-radius': '8px',
      '--app-font-family': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    densityMetrics: {
      paddingCard: 'p-4 sm:p-5',
      paddingButton: 'px-3.5 py-2 text-xs sm:text-sm',
      gapSection: 'space-y-5 gap-4',
      fontSizeBody: 'text-sm',
      fontSizeHeading: 'text-2xl font-bold tracking-tight',
      tableRowHeight: 'py-2.5 px-3 text-xs sm:text-sm',
      codeFontSize: 'text-xs font-mono',
    },
  },

  platform: {
    id: 'theme-platform',
    tabId: 'platform',
    name: 'Architectural Blueprint Cobalt',
    focusArea: 'Platform Architecture & VLA Engine',
    tagline: 'Technical Cobalt Matrix with Structured System Topology',
    description: 'Engineered for multi-modal model diagrams, tensor sharding schematics, and component graphs.',
    appearance: 'light',
    recommendedDensity: 'balanced',
    fontVibe: 'clean-slate',
    palette: {
      bg: '#f8fafc',
      bgGradient: 'radial-gradient(circle at 100% 0%, rgba(37, 99, 235, 0.06), #f8fafc)',
      bgSubtle: '#f1f5f9',
      surface: '#ffffff',
      surfaceRaised: '#ffffff',
      surfaceHover: '#f8fafc',
      border: '#e2e8f0',
      borderStrong: '#cbd5e1',
      borderHighlight: '#2563eb',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textMuted: '#64748b',
      accent: '#2563eb',
      accentHover: '#1d4ed8',
      accentLight: 'rgba(37, 99, 235, 0.1)',
      accentText: '#1e40af',
      accentGlow: '0 0 20px rgba(37, 99, 235, 0.2)',
      badgeBg: '#eff6ff',
      badgeText: '#1e40af',
      codeBg: '#0f172a',
      codeText: '#60a5fa',
      headerBg: 'rgba(255, 255, 255, 0.95)',
      sidebarBg: '#f8fafc',
    },
    cssVariables: {
      '--app-bg': '#f8fafc',
      '--app-surface': '#ffffff',
      '--app-surface-raised': '#ffffff',
      '--app-border': '#e2e8f0',
      '--app-border-strong': '#cbd5e1',
      '--app-text-primary': '#0f172a',
      '--app-text-secondary': '#475569',
      '--app-text-muted': '#64748b',
      '--app-accent': '#2563eb',
      '--app-accent-rgb': '37, 99, 235',
      '--app-accent-glow': 'rgba(37, 99, 235, 0.25)',
      '--app-card-radius': '8px',
      '--app-font-family': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    densityMetrics: {
      paddingCard: 'p-4 sm:p-6',
      paddingButton: 'px-3.5 py-2 text-xs sm:text-sm',
      gapSection: 'space-y-6 gap-4',
      fontSizeBody: 'text-sm',
      fontSizeHeading: 'text-2xl font-bold tracking-tight',
      tableRowHeight: 'py-2.5 px-3 text-sm',
      codeFontSize: 'text-xs font-mono',
    },
  },

  assistant: {
    id: 'theme-assistant',
    tabId: 'assistant',
    name: 'Creative Radiant Iris',
    focusArea: 'Assistant Creator & Simulator',
    tagline: 'Vibrant Lavender & Radiant Violet Innovation Studio',
    description: 'Dynamic conversational interface tuned for persona crafting, prompt testing, and simulation dialogue.',
    appearance: 'light',
    recommendedDensity: 'balanced',
    fontVibe: 'sans-modern',
    palette: {
      bg: '#faf8ff',
      bgGradient: 'radial-gradient(ellipse at 70% 0%, rgba(139, 92, 246, 0.12), #faf8ff)',
      bgSubtle: '#f3eefc',
      surface: '#ffffff',
      surfaceRaised: '#ffffff',
      surfaceHover: '#faf7fe',
      border: '#e9dff7',
      borderStrong: '#d8bdf2',
      borderHighlight: '#7c3aed',
      textPrimary: '#1e1035',
      textSecondary: '#5a4970',
      textMuted: '#7f6f96',
      accent: '#7c3aed',
      accentHover: '#6d28d9',
      accentLight: 'rgba(124, 58, 237, 0.12)',
      accentText: '#6d28d9',
      accentGlow: '0 0 22px rgba(124, 58, 237, 0.28)',
      badgeBg: '#f5f0ff',
      badgeText: '#6b21a8',
      codeBg: '#1e1035',
      codeText: '#c084fc',
      headerBg: 'rgba(250, 248, 255, 0.95)',
      sidebarBg: '#f5f0fc',
    },
    cssVariables: {
      '--app-bg': '#faf8ff',
      '--app-surface': '#ffffff',
      '--app-surface-raised': '#ffffff',
      '--app-border': '#e9dff7',
      '--app-border-strong': '#d8bdf2',
      '--app-text-primary': '#1e1035',
      '--app-text-secondary': '#5a4970',
      '--app-text-muted': '#7f6f96',
      '--app-accent': '#7c3aed',
      '--app-accent-rgb': '124, 58, 237',
      '--app-accent-glow': 'rgba(124, 58, 237, 0.3)',
      '--app-card-radius': '10px',
      '--app-font-family': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    densityMetrics: {
      paddingCard: 'p-5 sm:p-6',
      paddingButton: 'px-4 py-2 text-sm',
      gapSection: 'space-y-6 gap-4',
      fontSizeBody: 'text-sm leading-relaxed',
      fontSizeHeading: 'text-2xl font-bold tracking-tight',
      tableRowHeight: 'py-3 px-3.5 text-sm',
      codeFontSize: 'text-xs font-mono',
    },
  },

  cognitive: {
    id: 'theme-cognitive',
    tabId: 'cognitive',
    name: 'Synaptic Mind Amethyst',
    focusArea: 'Cognitive Architecture & Vector RAG',
    tagline: 'Deep Neural Night with Synaptic Violet & Vector Gold Pulses',
    description: 'Optimized for vector embedding visualizations, neural working memory loops, and semantic retrieval graphs.',
    appearance: 'dark',
    recommendedDensity: 'balanced',
    fontVibe: 'cyber-tech',
    palette: {
      bg: '#0c0a17',
      bgGradient: 'radial-gradient(circle at 50% 10%, rgba(168, 85, 247, 0.18), rgba(12, 10, 23, 1))',
      bgSubtle: '#141026',
      surface: '#17132c',
      surfaceRaised: '#221c3f',
      surfaceHover: '#29224d',
      border: '#2b234d',
      borderStrong: '#433777',
      borderHighlight: '#c084fc',
      textPrimary: '#f5f3ff',
      textSecondary: '#a79bc8',
      textMuted: '#7c709c',
      accent: '#a855f7',
      accentHover: '#c084fc',
      accentLight: 'rgba(168, 85, 247, 0.18)',
      accentText: '#e9d5ff',
      accentGlow: '0 0 24px rgba(168, 85, 247, 0.4)',
      badgeBg: 'rgba(168, 85, 247, 0.2)',
      badgeText: '#d8b4fe',
      codeBg: '#090812',
      codeText: '#fbbf24',
      headerBg: 'rgba(12, 10, 23, 0.95)',
      sidebarBg: '#120e24',
    },
    cssVariables: {
      '--app-bg': '#0c0a17',
      '--app-surface': '#17132c',
      '--app-surface-raised': '#221c3f',
      '--app-border': '#2b234d',
      '--app-border-strong': '#433777',
      '--app-text-primary': '#f5f3ff',
      '--app-text-secondary': '#a79bc8',
      '--app-text-muted': '#7c709c',
      '--app-accent': '#a855f7',
      '--app-accent-rgb': '168, 85, 247',
      '--app-accent-glow': 'rgba(168, 85, 247, 0.4)',
      '--app-card-radius': '8px',
      '--app-font-family': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    densityMetrics: {
      paddingCard: 'p-4 sm:p-5',
      paddingButton: 'px-3.5 py-2 text-xs sm:text-sm',
      gapSection: 'space-y-5 gap-4',
      fontSizeBody: 'text-xs sm:text-sm',
      fontSizeHeading: 'text-2xl font-bold tracking-tight',
      tableRowHeight: 'py-2.5 px-3 text-xs sm:text-sm',
      codeFontSize: 'text-xs font-mono',
    },
  },

  home: {
    id: 'theme-home',
    tabId: 'home',
    name: 'Apex Executive Minimalist',
    focusArea: 'Platform Overview & Mission Hub',
    tagline: 'Refined Obsidian & Alabaster with High-Definition Contrast',
    description: 'The master overview theme: balanced contrast, crystal-clear modular cards, and responsive executive metrics.',
    appearance: 'light',
    recommendedDensity: 'balanced',
    fontVibe: 'sans-modern',
    palette: {
      bg: '#fcfcfd',
      bgGradient: 'linear-gradient(180deg, #fcfcfd 0%, #f8fafc 100%)',
      bgSubtle: '#f1f5f9',
      surface: '#ffffff',
      surfaceRaised: '#ffffff',
      surfaceHover: '#f8fafc',
      border: '#e2e8f0',
      borderStrong: '#cbd5e1',
      borderHighlight: '#0f172a',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textMuted: '#64748b',
      accent: '#0f172a',
      accentHover: '#1e293b',
      accentLight: 'rgba(15, 23, 42, 0.08)',
      accentText: '#0f172a',
      accentGlow: '0 0 18px rgba(15, 23, 42, 0.15)',
      badgeBg: '#f1f5f9',
      badgeText: '#0f172a',
      codeBg: '#0f172a',
      codeText: '#38bdf8',
      headerBg: 'rgba(255, 255, 255, 0.95)',
      sidebarBg: '#f8fafc',
    },
    cssVariables: {
      '--app-bg': '#fcfcfd',
      '--app-surface': '#ffffff',
      '--app-surface-raised': '#ffffff',
      '--app-border': '#e2e8f0',
      '--app-border-strong': '#cbd5e1',
      '--app-text-primary': '#0f172a',
      '--app-text-secondary': '#475569',
      '--app-text-muted': '#64748b',
      '--app-accent': '#0f172a',
      '--app-accent-rgb': '15, 23, 42',
      '--app-accent-glow': 'rgba(15, 23, 42, 0.2)',
      '--app-card-radius': '8px',
      '--app-font-family': 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    },
    densityMetrics: {
      paddingCard: 'p-5 sm:p-6',
      paddingButton: 'px-4 py-2 text-sm',
      gapSection: 'space-y-6 gap-5',
      fontSizeBody: 'text-sm',
      fontSizeHeading: 'text-2xl sm:text-3xl font-bold tracking-tight',
      tableRowHeight: 'py-3 px-4 text-sm',
      codeFontSize: 'text-xs font-mono',
    },
  },
};

export const DEFAULT_THEME = FOCUS_AREA_THEMES.home;

export function getThemeForTab(tabId: string): FocusAreaTheme {
  return FOCUS_AREA_THEMES[tabId] || FOCUS_AREA_THEMES.home;
}
